"""Password hashing, secret-token handling, and JWT issuance.

Two different hashing strategies are used deliberately:

* Operator passwords are low-entropy, user-chosen secrets, so they go through
  Argon2id (`argon2-cffi`), which is deliberately slow and memory-hard.
* Enrollment tokens and per-agent keys are high-entropy secrets generated by
  the server itself (`secrets.token_urlsafe`), not chosen by a human. For
  those, a fast SHA-256 hash compared in constant time is the standard
  approach (the same one API-key systems such as GitHub's use) — Argon2 would
  only add CPU cost without a security benefit, since there is no low-entropy
  input to slow an attacker down against.
"""

import hashlib
import hmac
import secrets
from datetime import UTC, datetime, timedelta
from typing import Any, NamedTuple

import jwt
from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError

from warden_server.config import get_settings

_password_hasher = PasswordHasher()


def hash_password(password: str) -> str:
    return _password_hasher.hash(password)


def verify_password(password: str, password_hash: str) -> bool:
    try:
        return _password_hasher.verify(password_hash, password)
    except VerifyMismatchError:
        return False


def generate_secret_token() -> str:
    """Generate a URL-safe, high-entropy secret (enrollment token or agent key)."""
    return secrets.token_urlsafe(32)


def hash_secret_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def verify_secret_token(token: str, token_hash: str) -> bool:
    return hmac.compare_digest(hash_secret_token(token), token_hash)


class TokenClaims(NamedTuple):
    """What a valid session token asserts: whose it is, and which version."""

    subject: str
    version: int


def create_access_token(subject: str, version: int) -> str:
    """Issue a session token for `subject` at the operator's current version.

    `version` is required, so a caller that mints a token cannot forget it: a
    token is refused once its operator's version has moved on (D-9), which is
    how a session is ended before it expires.
    """
    settings = get_settings()
    expires_at = datetime.now(UTC) + timedelta(minutes=settings.jwt_expire_minutes)
    payload: dict[str, Any] = {"sub": subject, "ver": version, "exp": expires_at}
    return jwt.encode(payload, settings.jwt_secret, algorithm=settings.jwt_algorithm)


def decode_access_token(token: str) -> TokenClaims | None:
    """Return the token's claims, or None if it is missing/invalid/expired.

    A token without an integer `ver` is invalid too. That covers a session
    issued before versions existed, which is refused once after the upgrade.
    A boolean is rejected explicitly because it is an `int` in Python.
    """
    settings = get_settings()
    try:
        payload = jwt.decode(
            token, settings.jwt_secret, algorithms=[settings.jwt_algorithm]
        )
    except jwt.PyJWTError:
        return None
    subject = payload.get("sub")
    version = payload.get("ver")
    if not isinstance(subject, str):
        return None
    if isinstance(version, bool) or not isinstance(version, int):
        return None
    return TokenClaims(subject=subject, version=version)
