"""initial schema

Revision ID: 59fb180e4891
Revises:
Create Date: 2026-09-15 12:43:25.078066

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import warden_server.db
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59fb180e4891"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("os", sa.String(length=64), nullable=False),
        sa.Column("agent_key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="agentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "enrolled_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "last_seen_at", warden_server.db.UTCDateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_key_hash"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column(
            "occurred_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "detail",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enrollment_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "expires_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "used_at", warden_server.db.UTCDateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "operators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "inventory_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "detected_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "added",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "removed",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "collected_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "hardware",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "software",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("WINDOW_REQUEST", name="taskkind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "window_start", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "window_end", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "DISPATCHED",
                "COMPLETED",
                "FAILED",
                name="taskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "completed_at", warden_server.db.UTCDateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "REMOVABLE_MEDIA",
                "PRINTING",
                "PROCESSES",
                "WEB",
                name="eventcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "occurred_at", warden_server.db.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("tasks")
    op.drop_table("inventory_snapshots")
    op.drop_table("inventory_changes")
    op.drop_table("operators")
    op.drop_table("enrollment_tokens")
    op.drop_table("audit_log")
    op.drop_table("agents")
    # ### end Alembic commands ###
